# Generated by Django 5.1.4 on 2024-12-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='specialization',
            field=models.CharField(default='Developer', max_length=255),
            preserve_default=False,
        ),
    ]
